// Author: Haowen Jiang
// Date: 30/05/2024
// Modified: 2026
// Display the formula generated by chatgpt correctly 
// in the markdown file
// Converts \( \) to $ $ and \[ \] to $$ $$
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void readFile(const char *filename, char **content, long *length) {
    FILE *file = fopen(filename, "rb");
    if (file == NULL) {
        fprintf(stderr, "无法打开文件 %s 进行读取\n", filename);
        exit(1);
    }

    fseek(file, 0, SEEK_END);
    *length = ftell(file);
    fseek(file, 0, SEEK_SET);

    *content = (char *)malloc(*length + 1);
    if (*content == NULL) {
        fprintf(stderr, "内存分配失败\n");
        exit(1);
    }

    fread(*content, 1, *length, file);
    (*content)[*length] = '\0';

    fclose(file);
}

void writeFile(const char *filename, const char *content) {
    FILE *file = fopen(filename, "wb");
    if (file == NULL) {
        fprintf(stderr, "无法打开文件 %s 进行写入\n", filename);
        exit(1);
    }

    fwrite(content, 1, strlen(content), file);
    fclose(file);
}

// Calculate the new length after conversion
long calculateNewLength(const char *str, long length) {
    long newLen = 0;
    long i = 0;
    while (i < length) {
        if (str[i] == '\\' && i + 1 < length) {
            if (str[i + 1] == '(' || str[i + 1] == ')') {
                // \( or \) -> $ (2 chars -> 1 char)
                newLen += 1;
                i += 2;
            } else if (str[i + 1] == '[' || str[i + 1] == ']') {
                // \[ or \] -> $$ (2 chars -> 2 chars)
                newLen += 2;
                i += 2;
            } else if (str[i + 1] == '*') {
                // \* -> * (2 chars -> 1 char, remove unnecessary escape)
                newLen += 1;
                i += 2;
            } else {
                newLen++;
                i++;
            }
        } else {
            newLen++;
            i++;
        }
    }
    return newLen;
}

// Perform the conversion
char* convertLatex(const char *src, long srcLen) {
    long newLen = calculateNewLength(src, srcLen);
    char *dest = (char *)malloc(newLen + 1);
    if (dest == NULL) {
        fprintf(stderr, "内存分配失败\n");
        exit(1);
    }

    long i = 0, j = 0;
    while (i < srcLen) {
        if (src[i] == '\\' && i + 1 < srcLen) {
            if (src[i + 1] == '(' || src[i + 1] == ')') {
                // \( or \) -> $
                dest[j++] = '$';
                i += 2;
            } else if (src[i + 1] == '[' || src[i + 1] == ']') {
                // \[ or \] -> $$
                dest[j++] = '$';
                dest[j++] = '$';
                i += 2;
            } else if (src[i + 1] == '*') {
                // \* -> * (remove unnecessary escape)
                dest[j++] = '*';
                i += 2;
            } else {
                dest[j++] = src[i++];
            }
        } else {
            dest[j++] = src[i++];
        }
    }
    dest[j] = '\0';
    return dest;
}

int main(int argc, char** argv) {
    if (argc < 2) {
        fprintf(stderr, "用法: %s <输入文件> [输出文件]\n", argv[0]);
        fprintf(stderr, "  将 markdown 文件中的 LaTeX 公式格式转换:\n");
        fprintf(stderr, "  \\( \\) -> $ $   (行内公式)\n");
        fprintf(stderr, "  \\[ \\] -> $$ $$ (块级公式)\n");
        fprintf(stderr, "  \\*   -> *      (移除多余转义)\n");
        return 1;
    }

    char *content;
    long length;
    readFile(argv[1], &content, &length);
    
    char *converted = convertLatex(content, length);
    
    // Output file: use argv[2] if provided, otherwise "output.md"
    const char *outputFile = (argc >= 3) ? argv[2] : "output.md";
    writeFile(outputFile, converted);
    
    free(content);
    free(converted);
    
    printf("转换成功! 输出文件: %s\n", outputFile);
    printf("  \\( \\) -> $ $\n");
    printf("  \\[ \\] -> $$ $$\n");
    printf("  \\*   -> *\n");

    return 0;
}
